### ISSUE TITLE
Good Luck!

### ISSUE THREAD

**Issue by EnderBrine101** [RedstoneLamp/RedstoneLamp#10]
Good luck on development! Is this going to have an API for mods? I mean like an API for ModPE (Yes, I know ModPE IS an API - but hopefully you get what I mean). Another suggestion would be to create a test server (So proplr can test it without download it).

**Comment by PEMapModder** [comment]
We will have a ModPE-like API in PocketBukkit ;)

**Comment by EnderBrine101** [comment]
Nice! @PEMapModder. Will it be like Server.setItem?

**Comment by PEMapModder** [comment]
No, PocketBukkit just has a server-side API designed like ModPE but not for ModPE.

**Comment by PhilipShilling** [comment]
We will probably implement ModPE at a later date :)

**Comment by jython234** [comment]
Just want to throw in my support too. Starting MCPE server projects is hard, I've done over 3 projects with countless rewrites. Good luck!

**Comment by EnderBrine101** [comment]
@jython234 Why dont you make a commit? :3

**Comment by PhilipShilling** [comment]
@jython234 Yeah. I end up constantly rewriting code because of my OCD. I end up not liking the layout of the code and want to start over. XD

**Comment by EnderBrine101** [comment]
@PhilipShilling Do you already have the login and disconnect packets? Also, I hsvr OCD too so CREATE A FOLDER CALLED ENTITES AND MOVE PLAYER.JAVA TO THERE

**Comment by EnderBrine101** [comment]
Have*

**Comment by PhilipShilling** [comment]
@EnderBrine101 Obsesive Cumpulsive Disorder would not make you feel the need at have something added. Player.java is not an entity. It is methods of registering players to the server. It will not be moved.

**Comment by EnderBrine101** [comment]
@PhilipSterling 
https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/entity/Player.java

**Comment by EnderBrine101** [comment]
Autocorrect, whoops @PhilipShilling

**Comment by PhilipShilling** [comment]
Why are you linking me this?... Player.java is the API for adding players to the server. Player.java has nothing to do with entities nor will it. That will be files like PlayerEntity.java, ZombieEntity.java, CowEntity.java, etc.

**Comment by EnderBrine101** [comment]
Probably got confused with that.

**Comment by PEMapModder** [comment]
@EnderBrine101 because this is not Bukkit. The end.

**Comment by jython234** [comment]
Well you need to implement custom packets better I think. The mysteries of
encapsulation take us all.

On Monday, April 20, 2015, PEMapModder <notifications@github.com> wrote:

> @EnderBrine101 <https://github.com/EnderBrine101> because this is not
> Bukkit. The end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/10#issuecomment-94390301>
> .
>


--
