### ISSUE TITLE
Player is "crouching" and moves really slow

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#105]
When a player joins, usually using a default skin (but this still happened with a custom one) they find themselves moving slowly, and if another one joins they can see that the other players' back is arched forward a bit.

**Comment by gskjold** [comment]
Removed PlayerEntity:47 (Metadata with key 17). After that everything works. Could also remove key 1, 4 and 15 with no difference in behavior. Maybe not necessary to set all of these at init? Just thinking out loud....

**Comment by jython234** [comment]
I believe this issue has been fixed
