### ISSUE TITLE
[RFC]: Use ProtocolSessions

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#106]
In BlockServer, we used ProtocolSessions to handle packets and reroute them to a Subprotocol. But, with the system we have now, the Protocol class interacts directly with the Subprotocols. This has raised a few concerns for me, one of them being Chunk sending. MCPE automatically unloads chunks in multiplayer, but the PC version requires the server to tell it to unload a chunk. Since not all protocols require chunk unloading, (some don't even require chunks at all), it has come to my attention to use a ProtocolSession for each session to handle some protocol specific tasks, such as chunk sending and chunk unloading.

##### Please comment your idea(s) below, and remember this is on branch ```rewrite```

**Comment by PEMapModder** [comment]
I think it is suitable that a chunk unload response being fired anyway, with no data being compiled for the response (like the chunk data, but only the X Z chunk coords for the subprotocol to interact with the chunk directly.

**Comment by jython234** [comment]
@PEMapModder ok.

On Saturday, August 29, 2015, PEMapModder <notifications@github.com> wrote:

> I think it is suitable that a chunk unload response being fired anyway,
> with no data being compiled for the response (like the chunk data, but only
> the X Z chunk coords for the subprotocol to interact with the chunk
> directly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/106#issuecomment-136084411>
> .
>


--
