### ISSUE TITLE
Permission Node ideas

### ISSUE THREAD

**Issue by EnderBrine101** [RedstoneLamp/RedstoneLamp#11]
I have put together a long list of permissjons coverin all commands that are in pocketmine but I have added a few that should be there. All the ones with ".others" after it means it can be done to others. For example you wanted to let somronr change someone elses gamemode "redstonelamp.command.gamemode.others" but if you wanted them to only change there own: "redstonelamp.command.gamemode"
https://db.tt/dnvZiKEn

Keep in mind that these are just ideas - that would allow full customizability with permission plugins. I reccomend adding some of these at least.

**Comment by EnderBrine101** [comment]
#1

**Comment by EnderBrine101** [comment]
(Not to spam or ajything) @PEMapModder

**Comment by PEMapModder** [comment]
@EnderBrine101 as @DASWAGNEMITE mentioned, don't use this like a forum, And don't tag me everywhere.
