### ISSUE TITLE
ModPE API To Create Plugins?

### ISSUE THREAD

**Issue by EnderBrine101** [RedstoneLamp/RedstoneLamp#12]
Sorry t spam with issues, but aswell as the ModPE API for using normal mods in the server you could also add an API for ModPE plugins. Such as a new command would use the normal function procCmd(cmd) like in ModPE. Sound like a good idea? (I mean after all the important stuff is done)

**Comment by EnderBrine101** [comment]
Seriously no reply?

**Comment by PhilipShilling** [comment]
This has basically been answered already
