### ISSUE TITLE
MCPC: RuntimeException (VarInt too big)

### ISSUE THREAD

**Issue by BasicStudyer** [RedstoneLamp/RedstoneLamp#122]
need help!

**Comment by jython234** [comment]
Pc is currently low priority, and this is a known issue. We are rewriting PC networking and this should be fixed.

**Comment by BasicStudyer** [comment]
thx for reply!

**Comment by SuperstarGamer** [comment]
I'll look at this, maybe this is my fault. I'm in charge of PC networking so I'll take a look at it :)

**Comment by SuperstarGamer** [comment]
Bug should be fixed!
