### ISSUE TITLE
Worlds not loading at all anymore

### ISSUE THREAD

**Issue by SuperstarGamer** [RedstoneLamp/RedstoneLamp#123]
For some reason, worlds are not loading anymore. This can be replicated just by starting the server. It happened when I generated a new one, maybe the generator is broke?

**Comment by jython234** [comment]
What do you mean they aren't loading anymore?

On Monday, September 28, 2015, Trent <notifications@github.com> wrote:

> For some reason, worlds are not loading anymore. This can be replicated
> just by starting the server. It happened when I generated a new one, maybe
> the generator is broke?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/123>.
>


--

**Comment by SuperstarGamer** [comment]
When you start the server it throws a nasty exception at now saying the Manifest file for the world isn't found even though it's clearly there.

**Comment by jython234** [comment]
@SuperstarGamer Use a fresh install/clone.

**Comment by SuperstarGamer** [comment]
I am using a fresh install/clone.

**Comment by jython234** [comment]
Using an IDE? Make sure your on the right branch and delete your worlds
folder.

On Monday, September 28, 2015, Trent <notifications@github.com> wrote:

> I am using a fresh install/clone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/123#issuecomment-143911544>
> .
>


--

**Comment by SuperstarGamer** [comment]
We're on branch rewrite correct?
And yes, I'm using Eclipse Mars. With Lombok and JUnit.

**Comment by SuperstarGamer** [comment]
@jython234  We're on branch rewrite correct?
And yes, I'm using Eclipse Mars. With Lombok and JUnit.
I also deleted the worlds folder so RedstoneLamp could generate a new world. It still failed.

**Comment by jython234** [comment]
@SuperstarGamer it seems that the LevelDB database is corrupted, check if your HDD is full. Also try running outside the IDE.

**Comment by SuperstarGamer** [comment]
@jython234 My HDD is nowhere near full, but I'll try running out of my IDE like you said.
