### ISSUE TITLE
Blocks shift to different chunks

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#124]
Blocks appear to shift after placement. For example, player A joins the server. They place a few blocks, then disconnect and rejoin. The blocks built are no longer in their positions before, but they move to a different chunk. This has been replicated on my private server and the public RedstoneLamp test server.

EDIT: this only appears to happen on a specific pre-packaged world, the one with the missing chunk.

**Comment by PhilipShilling** [comment]
Is this an issue with the way the world saved or block placement in general?

**Comment by jython234** [comment]
@PhilipShilling I think it has something to do with modifying blocks in the Chunk class. It needs to be replicated on other worlds first though.
