### ISSUE TITLE
[MultiCraft] MultiCraft creates server.properties before RedstoneLamp causing crashes

### ISSUE THREAD

**Issue by PhilipShilling** [RedstoneLamp/RedstoneLamp#125]
When RedstoneLamp is setup for use with MultiCraft, multicraft creates a basic server.properties file before RedstoneLamp launches, this causes the server to crash due to missing properties that are required.

Stack Trace:
30.09 15:22:39 [Server] INFO Exception in thread "main" java.lang.NumberFormatException: null
30.09 15:22:39 [Server] INFO at java.lang.Integer.parseInt(Integer.java:542)
30.09 15:22:39 [Server] INFO at java.lang.Integer.parseInt(Integer.java:615)
30.09 15:22:39 [Server] INFO at net.redstonelamp.config.ServerConfig.getInt(ServerConfig.java:70)
30.09 15:22:39 [Server] INFO at net.redstonelamp.network.pe.JRakLibInterface.<init>(JRakLibInterface.java:62)
30.09 15:22:39 [Server] INFO at net.redstonelamp.network.pe.PEProtocol.<init>(PEProtocol.java:59)
30.09 15:22:39 [Server] INFO at net.redstonelamp.Server.<init>(Server.java:95)
30.09 15:22:39 [Server] INFO at net.redstonelamp.RedstoneLamp.main(RedstoneLamp.java:54)

**Comment by PEMapModder** [comment]
Possible solution: add a redstonelamp identifier for server.properties
