### ISSUE TITLE
Packets after login are not received by clients at random times

### ISSUE THREAD

**Issue by SuperstarGamer** [RedstoneLamp/RedstoneLamp#126]
Sometimes when a player spawns in, no other packets are received/handled by the server randomly. I have no idea what causes this.

**Comment by PhilipShilling** [comment]
Is this on MCPE or MCPC?

**Comment by SuperstarGamer** [comment]
@PhilipShilling It is MCPE, but it might apply to MCPC as well. I am starting to think this might have something to do with address blocking? I'll do a debug to see when addresses are being blocked.

**Comment by jython234** [comment]
@SuperstarGamer if an address is blocked, it shows up in the console.

On Thursday, October 1, 2015, Trent <notifications@github.com> wrote:

> @PhilipShilling <https://github.com/PhilipShilling> It is MCPE, but it
> might apply to MCPC as well. I am starting to think this might have
> something to do with address blocking? I'll do a debug to see when
> addresses are being blocked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/126#issuecomment-144880614>
> .
>


--

**Comment by SuperstarGamer** [comment]
@jython234 Can you come onto IRC?

**Comment by SuperstarGamer** [comment]
@jython234 @PhillipShilling It seems like this has to do with the ticking system. It's freezing up, maybe things like packet handling shouldnt be tied to the ticker system and on its own thread? That's what bukkit and spigot do. I did a test and it works SO much better than using the ticker system but instead on it's own thread. Things like crops, timing, time of day, etc. should be handled by the ticker?

**Comment by jython234** [comment]
This has been confirmed to be a system-specific issue to @SuperstarGamer. If you are having this issue too, please comment here so we can re-open it.
