### ISSUE TITLE
redstonelamp.net is offline

### ISSUE THREAD

**Issue by Jelly9912** [RedstoneLamp/RedstoneLamp#129]
http://zapodaj.net/images/5462c5ef48665.png

**Comment by PEMapModder** [comment]
This is not a RedstoneLamp issue.

**Comment by jython234** [comment]
@PEMapModder the site is still down.

On Saturday, October 10, 2015, PEMapModder <notifications@github.com> wrote:

> Closed #129 <https://github.com/RedstoneLamp/RedstoneLamp/issues/129>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/129#event-432069241>.
>


--

**Comment by PhilipShilling** [comment]
Again, this is a known thing. I am working on getting this fixed.
