### ISSUE TITLE
Do you need command descriptions?

### ISSUE THREAD

**Issue by EnderBrine101** [RedstoneLamp/RedstoneLamp#13]
Do you need command dscriptions such as "/kill - Kills You"

**Comment by PhilipShilling** [comment]
This kind of thing should be posted on the forums however, when registering commands the second parameter is the commands description. This is required for the help command to explain commands to the users properly.

**Comment by EnderBrine101** [comment]
But for the default command do you want me to do the descriptions based on normal minecraft ones? EDIT: i get what you mean now.
