### ISSUE TITLE
The websites are down

### ISSUE THREAD

**Issue by 202831820** [RedstoneLamp/RedstoneLamp#132]
RedstoneLamp - http://RedstoneLamp.net

RedstoneLamp Forums - http://forums.RedstoneLamp.net

RedstoneLamp Documentation - http://docs.RedstoneLamp.net

Get Plugins - http://forums.RedstoneLamp.net/resources/

**Comment by PEMapModder** [comment]
These are website issues, not RedstoneLamp issues.

**Comment by PhilipShilling** [comment]
Just to add on to what @PEMapModder said, we are aware that the websites are down but this is not an issue with the software itself, the website should be back up soon.  Please check out twitter to stay updated: http://twitter.com/RedstoneLampMP
