### ISSUE TITLE
redstonelamp.net is a purchased domain but has no site

### ISSUE THREAD

**Issue by mhsjlw** [RedstoneLamp/RedstoneLamp#140]
If you weren't aware already, now you are!

**Comment by legoboy0215** [comment]
Everyone is aware...

**Comment by jython234** [comment]
The website is down, but the project isn't dead.

On Saturday, October 24, 2015, mhsjlw <notifications@github.com> wrote:

> Closed #140 <https://github.com/RedstoneLamp/RedstoneLamp/issues/140>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/140#event-444554891>.
>


--
