### ISSUE TITLE
Why not merge some features from branch New to Master?

### ISSUE THREAD

**Issue by EnderBrine101** [RedstoneLamp/RedstoneLamp#28]
I saw in the branch "New" you already have packets setup. Im not sure if it is fully complete as I am not familiar with the Minecraft Pocket Edition Protocal. Why dont you merge it wish the Master branch? Is there something preventing you?

**Comment by PhilipShilling** [comment]
The new branch was to clean the code up. Right now the master branch is sloppy. I am working (inside of eclipse) on moving things over to new

**Comment by EnderBrine101** [comment]
@PhilipShilling I made a pull request for adding server.propertied. get denied. How come its now in there?

**Comment by PhilipShilling** [comment]
What was it you added?

**Comment by EnderBrine101** [comment]
I did add some unercerary things, well, in the future they would be useful. Its fine. Doesnt matter.

**Comment by PhilipShilling** [comment]
The server.properties has existed since 1.1.0 was started...

**Comment by EnderBrine101** [comment]
Oh. I didnt realise because it was in the "New" branch. Also i need you to check your PM's on redstonelamp.net because the  minecraft forum admins are relentless.
