### ISSUE TITLE
Idea.

### ISSUE THREAD

**Issue by EnderBrine101** [RedstoneLamp/RedstoneLamp#29]
Since im learning how to make windows applications, I was wondering if (closer to the time) I could make a launcher for different versions. You may be like "Woah, woah different version?!"
Well I was thinking this: 
We could have a version for just vanilla - no plugin support. This shouldnt be too hard because you just remove all plugin related items. This is not essentials.
A version that includes plugins and/or modding API.
And obviously all older versions of the software available from a simple drop doen menu.
Sound good future plan? Feel free to elaborate on this idea.

Before you moan about me posting in the issues section, lots of people do it. Make a rule about not doing it. In fact I wont do it again. Sound good?

**Comment by PhilipShilling** [comment]
A vanilla feature is planned to be added to the server properties by 1.2.1

**Comment by PEMapModder** [comment]
@PhilipShilling please add a CONTRIBUTING.md

**Comment by EnderBrine101** [comment]
@PEMapModder Haha, Good idea.

**Comment by PhilipShilling** [comment]
@PEMapModder I was planning on doing that after I get packet 0x01 working :P

**Comment by EnderBrine101** [comment]
What is packets 0x01? I cant be bothered to search.

**Comment by EnderBrine101** [comment]
Can you please notify me when the server sends the login packets so we can actually join a world? I will get this person i know to run a test server (He already agreed)

**Comment by PhilipShilling** [comment]
Packet 0x01 is to ping the server from the main menu. 

http://wiki.vg/Pocket_Minecraft_Protocol#ID_CONNECTED_PING_OPEN_CONNECTIONS_.280x01.29

**Comment by PhilipShilling** [comment]
@PEMapModder CINTRIBUTING.md made :)

**Comment by EnderBrine101** [comment]
@PhilipShilling Does the server name and description now show up on the world screen?

**Comment by PhilipShilling** [comment]
That is what I am trying to implement now. The server gets it, it just needs to send a Pong packet

**Comment by EnderBrine101** [comment]
Please tell mr when its done! Thanks :D
