### ISSUE TITLE
Help?!

### ISSUE THREAD

**Issue by EnderBrine101** [RedstoneLamp/RedstoneLamp#33]
I get this on the dev build:

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\CENSORED>cd C:\Users\CENDORED\Desktop

C:\Users\CENDORED\Desktop>java -jar RedstoneLamp.jar
17:22:09 [INFO] Loading server properties...
17:22:10 [INFO] Starting Minecraft: PE server on 192.168.56.1:19132
17:22:12 [INFO] Done! For help, type "help" or "?"
17:22:17 [DEBUG] No packets recieved in the last 5 seconds
17:22:22 [DEBUG] No packets recieved in the last 5 seconds

**Comment by PEMapModder** [comment]
What's wrong with it?

**Comment by EnderBrine101** [comment]
@PEMapModder Isint it ment to not say "No packets recieved"? I know packets arent fully implemented but in a forums.redstonelamp.net post there was a tutorial on how to install. It didnt show this. Maybe because it was an older version?

**Comment by PhilipShilling** [comment]
The No Packets Recieved thing is fine. Its just saying that no clients have sent anything to the server the the last 5 seconds.
