### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Ivanzar** [RedstoneLamp/RedstoneLamp#61]
I don't understand where the plugins folder

**Comment by RandomAltThing** [comment]
Try looking in C://User/YOURUSER

I'm not sure if that is the exact file path, but basically you look in the C:// drive then the user folder. After that click your user name folder. It may be in there I'm not sure.

**Comment by PhilipShilling** [comment]
The plugins folder is created in the same folder as RedstoneLamp on it's first launch.

**Comment by RandomAltThing** [comment]
@PhilipShilling The question is, where **IS** the RedstoneLamp folder?

**Comment by PhilipShilling** [comment]
The RedstoneLamp folder is the folder that contains your server Jar and start.exe/start.sh

**Comment by Ivanzar** [comment]
I do not have this folder was created, but the main issue is that the server is not visible in status as an example PocketMine

**Comment by PhilipShilling** [comment]
The console window does not currently have that function and is a low priority feature

**Comment by Ivanzar** [comment]
https://www.dropbox.com/s/s8uy4b1tq792a0q/Screenshot_2015-05-12-19-15-28.jpg?dl=0

**Comment by RandomAltThing** [comment]
@Ivanzar This is not currently implemented, the client cannot yet find the server u.till the essential packets are done. Sorry about that.

**Comment by PhilipShilling** [comment]
Actually that is a bug.  The server does send the QueryResponsePacket bug as of either 0.11.0 build 8 or build 9 the client does not properly receive the response. This should be fixed soon.

**Comment by RandomAltThing** [comment]
Well if this is a bug, could you lock it and add the bug tag?

**Comment by PhilipShilling** [comment]
No because this issue was originally about the plugins folder.
