### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by Ivanzar** [RedstoneLamp/RedstoneLamp#62]
did not work, the server does not even show the status of

**Comment by RandomAltThing** [comment]
@Ivanzar Please do not create spam issues. *You may be banned from this repository*

**Comment by Ivanzar** [comment]
@RandomAltThing  OK, but you couldn't tell me why it is do not work?

**Comment by Ivanzar** [comment]
I unpacked the archive, put in  it RedstoneLamp.jar, and launched

**Comment by PhilipShilling** [comment]
@RandomAltThing please do not pretend to be a member of the organization...

@Ivanzar please give a little more information as to what your issue is.

**Comment by RandomAltThing** [comment]
@PhilipShilling I am not. I merely stated *"You may be banned"*. Meaning you, or someone else within the organisation could possibly block this person for spam. That is all.

**Comment by Ivanzar** [comment]
@PhilipShilling no plugins folder, the server does not work. I have build 9

**Comment by Ivanzar** [comment]
https://www.dropbox.com/s/cjajqmje8mc9l7l/%D0%91%D0%B5%D0%B7%D1%8B%D0%BC%D1%8F%D0%BD%D0%BD%D1%8B%D0%B9.png?dl=0

**Comment by PhilipShilling** [comment]
Your image is too blurry. What does the console say?

**Comment by RandomAltThing** [comment]
Invalid answer. I asked where is the folder and not what the contents were.

**Comment by goerick** [comment]
Did you do cd Command?

**Comment by goerick** [comment]
Also if you can give us a good high definition picture maybe we can trouble shoot what is your problem. I'm a windows user so I can /probably/ solve your problem As it works perfectly for me

**Comment by Ivanzar** [comment]
https://www.dropbox.com/s/s8uy4b1tq792a0q/Screenshot_2015-05-12-19-15-28.jpg?dl=0

**Comment by jython234** [comment]
BlockServer has the same problem.

**Comment by jython234** [comment]
@Ivanzar #67

**Comment by goerick** [comment]
@Ivanzar downgrade to 10.4
