### ISSUE TITLE
Must read

### ISSUE THREAD

**Issue by RandomAltThing** [RedstoneLamp/RedstoneLamp#63]
When the account is unblocked, delete everything (Don't unmerge, delete pending) PRs from EnderBrine101

**Comment by PhilipShilling** [comment]
Please read the CONTRIBUTING.md file

**Comment by PEMapModder** [comment]
A side note, @EnderBrine101 was deleted by GitHub. It will not be reversed.

**Comment by jython234** [comment]
Why was his account deleted?

On Tuesday, May 12, 2015, PEMapModder <notifications@github.com> wrote:

> A side note, @EnderBrine101 <https://github.com/EnderBrine101> was
> deleted by GitHub. It will not be reversed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/63#issuecomment-101219616>
> .
>


--

**Comment by RandomAltThing** [comment]
@PEMapModder My account was hidden. Do you need to see proof by the Github staff or will you continue to be a bitch?

**Comment by RandomAltThing** [comment]
![2015_05_13_07 26 34](https://cloud.githubusercontent.com/assets/12383507/7604948/d8d5ecde-f941-11e4-93bc-4857db4c2314.png)

**Comment by RandomAltThing** [comment]
Its unblocked
