### ISSUE TITLE
ID_UNCONNECTED_PING_OPEN_CONNECTIONS (0x1C) fails to advertise to client

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#67]
Client does not recognize server on the server list as of 0.11.0 build (6?). This does not affect 0.10.4 clients. This issue has been replicated by me and BlockServer.

**Comment by PhilipShilling** [comment]
This is fixed in a closed build version

**Comment by jython234** [comment]
I forgotten about this issue, the identifier format has changed. All good :)
