### ISSUE TITLE
How long untill its read?

### ISSUE THREAD

**Issue by yungtechboy1** [RedstoneLamp/RedstoneLamp#71]
JUst Wanted to Know. Seems like someing I would use!

**Comment by yungtechboy1** [comment]
I would love to pay you to complete it for me :)

**Comment by PhilipShilling** [comment]
In the background we are working on Level generation and client spawning.  We do not require any payment but donations are accepted. :)

To answer your questoin: we do not have an exact date as to when it will be ready for testing.

**Comment by PEMapModder** [comment]
This project is open-source. It will not be completed only "for me".
