### ISSUE TITLE
[RFC 1] New license

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#75]
As @wiez already said, the license would not hold up in court, and the fact that people arn't allowed to modify the code without making a pull/pushing doesn't make any sense, and the license is vague. I suggest we change the license to a different one, such as GPL v3.

**Comment by PhilipShilling** [comment]
Done

**Comment by PhilipShilling** [comment]
LOL removing Java7 fixed Travis.
