### ISSUE TITLE
JRakLib issues on Windows 10

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#84]
Apparently jraklib sends the packet, but does not show up on wireshark. Using the debugger, the socket.send method is called, so it must be a Java issue.

**Comment by PhilipShilling** [comment]
Probably a compatibility issue since Windows 10 just came out :P

**Comment by jython234** [comment]
@PhilipShilling That's probably what I was thinking, I'll update java and see what happens.

**Comment by jython234** [comment]
This issue has now been resolved on my system. If anyone has a similar problem, comment here.

**Comment by unnivm** [comment]
could you tell me when  it is "SENDING" ?



On Tue, Aug 4, 2015 at 3:50 AM, jython234 <notifications@github.com> wrote:

> Apparently jraklib sends the packet, but does not show up on wireshark.
> Using the debugger, the socket.send method is called, so it must be a Java
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/84>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>
