### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by RandomAltThing** [RedstoneLamp/RedstoneLamp#85]
I cannot build this project as it doesn't recognise it as a java project. Maybe because the .project file is missing?

**Comment by jython234** [comment]
What IDE are you using? Try creating a new java project, and copy and paste the src files.

**Comment by RandomAltThing** [comment]
@jython234 I was using Eclipse, but I'm not an expert at that so I git cloned using AIDE on my phone and I could open the project but I get errors. I added all the libraries and everything but it still happens.

**Comment by PhilipShilling** [comment]
All you need to do is create a java project with the source folder pointed to the RedstoneLamp root

**Comment by jython234** [comment]
@RandomAltThing If you have more issues setting up, pm us on the forums.
