### ISSUE TITLE
Player Kicking Issue

### ISSUE THREAD

**Issue by PhilipShilling** [RedstoneLamp/RedstoneLamp#86]
Kicking a player from the server seems to make the server think the player has disconnected but the client isnt given a message that it was removed but remains in the world.

**Comment by jython234** [comment]
That's because the client is messed up since we told it to spawn but
there's no chunks (the ones we send don't seem to be right). The client
will also not open the pause menu or chat. It's weird.

On Tuesday, August 4, 2015, Philip Shilling <notifications@github.com>
wrote:

> Kicking a player from the server seems to make the server think the player
> has disconnected but the client isnt given a message that it was removed
> but remains in the world.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/86>.
>


--

**Comment by PhilipShilling** [comment]
I figured it had something to do with that after I posted it because i saw chat didnt open either.

**Comment by jython234** [comment]
It's happened before, I just need to get the chunks right.

On Tuesday, August 4, 2015, Philip Shilling <notifications@github.com>
wrote:

> I figured it had something to do with that after I posted it because i saw
> chat didnt open either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/86#issuecomment-127628386>
> .
>


--

**Comment by jython234** [comment]
@PhilipShilling This has been fixed?

**Comment by PhilipShilling** [comment]
Yeah it works fine

**Comment by PhilipShilling** [comment]
@jython234 It looks like if you do player.kick("reason", false); it fails but player.kick("reason", true); works fine.
