### ISSUE TITLE
PEMapModder

### ISSUE THREAD

**Issue by RandomAltThing** [RedstoneLamp/RedstoneLamp#92]
@PhilipShilling So I am banned on IRC and on the forums because of @PEMapModder. He complains that I translated code from pocketmine then he said that RedstoneLamp translates code from pocketmine aswell, try looking at the <code>SetDifficultyPacket.java and SetHealthPacket.java and PENetworkInfo.java</code>. I do the same thing. 

I am not sure why I am banned, (Well @PEMapModder did say he was trying to deliberatly annoy me), but all I'm trying to do is help. I'm spending **my** time to contribute code to this project. It looks the most promising out of all mcpe server projects.

**Comment by PhilipShilling** [comment]
Please do not abuse the issues.

**Comment by jython234** [comment]
Lol @PEMapModder is not an issue.

**Comment by Gamecrafter** [comment]
@RandomAltThing I think everyone here considers you a nuisance.
