### ISSUE TITLE
Players can't see each other build.

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#97]
Players can't see each other build blocks on branch ```anvil-level-support```

This issue has been reproduced on @SuperstarGamer's server, and the RedstoneLamp public testing server.

**Comment by PEMapModder** [comment]
@jython234 don't you think you are misusing the `Help Wanted` label?

**Comment by legoboy0215** [comment]
He does have HelpWanted...

**Comment by jython234** [comment]
We'll help is wanted, I can't be Shoghicp you know.

On Tuesday, September 8, 2015, legoboy0215 <notifications@github.com> wrote:

> He does have HelpWanted...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/97#issuecomment-138511040>
> .
>


--
