### ISSUE TITLE
[REWRITE] Player spawns on world, then falls through ground

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#98]
The player spawns on the grass world, then they fall through the ground into the void.
 If you are able to reproduce this, please comment below.

**Comment by PhilipShilling** [comment]
Not able to replicate. Worked fine for me from the looks of it.

**Comment by gskjold** [comment]
Happens every time with me. Looks to me like I spawn inside the dirt layer, not on top of it.
If I change LevelDBProvider:161 to level.setSpawnPosition(new Position(x, y+2, z, level)), I spawn on top of the layer. Tried first to change LevelDBProvider:109 to a value greater than 1, but always fell through. Assuming that level is created relative to spawn point, but also on top of it.

**Comment by jython234** [comment]
I see. I'll have to see if creating another layer of grass does th job, and
the spawn position issue.

On Wednesday, August 26, 2015, Gunnar Skjold <notifications@github.com>
wrote:

> Happens every time with me. Looks to me like I spawn inside the dirt
> layer, not on top of it.
> If I change LevelDBProvider:161 to level.setSpawnPosition(new Position(x,
> y+2, z, level)), I spawn on top of the layer. Tried first to change
> LevelDBProvider:109 to a value greater than 1, but always fell through.
> Assuming that level is created relative to spawn point, but also on top of
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/98#issuecomment-134853727>
> .
>


--

**Comment by jython234** [comment]
Fixed on branch ```rewrite```
