### ISSUE TITLE
When a message is sent, a phantom line is created

### ISSUE THREAD

**Issue by SuperstarGamer** [RedstoneLamp/RedstoneLamp#99]
Whenever a message is sent, the message is sent successfully, but then a phantom line is created. This causes weird message formats to appear.

Example:
"This is message 1"
"                            " <- The phantom line
"This is message 2"
"                           " <- Another one is created, but you don't notice it because it's invisible until another message is sent

**Comment by PhilipShilling** [comment]
Check if it creates a second line on send using \n or similar

**Comment by PEMapModder** [comment]
Maybe `\n`

**Comment by jython234** [comment]
Fixed on branch ```rewrite```
